### ISSUE TITLE
Namespaces are no longer moved to top of file

### ISSUE THREAD

**Issue by davkean** [dotnet/codeformatter#168]
It appears in recent builds namespaces are no longer moved, whereas, https://github.com/dotnet/codeformatter/releases/tag/v1.0.0-alpha5 did move them:

Have this:

``` C#
namespace Microsoft.VisualStudio.ProjectSystem
{
    using System;

    [...]
}
```

Expected:

``` C#
using System;

namespace Microsoft.VisualStudio.ProjectSystem
{
    [...]
}
```

Actual:

``` C#
namespace Microsoft.VisualStudio.ProjectSystem
{
    using System;    

    [...]
}
```

**Comment by jaredpar** [comment]
We deliberately decided to disable this rule by default because it's simply unsafe to run in it's current form.  Moving a using around has a subtle but significant impact on name lookup in the compiler.  It's possible for this to create compilation errors or even silent redirections to new types.  That goes against the operating principles of code formatter and hence it was disabled by default.
